### ISSUE TITLE
Detect when the site is on a different domain/etc than the one PMPro was installed on.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#1034]
**Is your feature request related to a problem? Please describe.**

Users will create a staging site containing live members and subscriptions. If and when users are deleted or expired from the staging site, PMPro will use the payment gateway APIs to cancel the associated subscription. Users are then cancelled on the live site.

**Describe the solution you'd like**

PMPro could keep track of the domain it was installed or last active on. We can check when loading the admin dashboard, and if the domain has changed, show a notice with information on running PMPro on staging sites.

We could also deactivate some cron jobs and gateway features (maybe use a filter to mask API keys effectively breaking them) until the user confirmed whether or not they want to keep this stuff disabled.

**Describe alternatives you've considered**

Alternatively, we could change our mind RE cancelling subscriptions when users are deleted. We are exploring that here: https://github.com/strangerstudios/paid-memberships-pro/issues/973

and here: https://github.com/strangerstudios/paid-memberships-pro/issues/688

This would only fix the issue when users are deleted. Users can also be cancelled on the staging site or expire via cron job. In these cases, we would want the users unsubscribed on the live site. So some sort of staging site detection is needed.

**Additional context**

Similar to the "hide from Google" option in WP, we will have cases where users might disable functionality on the staging site. Then when they push staging to production, we would need to detect that again so we can prompt them to reenable features they might have disabled.

**Comment by mircobabini** [comment]
This is a basic class to start working on it: https://gist.github.com/mircobabini/0640e451e96c2dfbc51e9bc2f1d83fc1

The source code is taken from WCS and refactored. Also, the source code about showing notices to the admin was removed because is worth checking some other implementations (WCS and WPML).

They are doing a great job about change url detection. Also worth considering:
1. Integration with [WP Staging](https://it.wordpress.org/plugins/wp-staging/)
1. Detect http -> https (easy way to activate SSL from WordPress 5.7+)
1. Detect WP environment wp_get_environment_type() from WordPress 5.5+ [feature announcement](https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/)

Pmpro lectures:
- https://www.paidmembershipspro.com/why-you-should-use-a-staging-environment/
- https://www.paidmembershipspro.com/how-to-set-up-a-staging-environment-to-test-changes-and-new-features-for-your-membership-site/

Must keep in mind to scrub data as soon as possible using [pmpro-toolkit](https://www.paidmembershipspro.com/add-ons/pmpro-toolkit/). Since there is no way back, can't push staging to production once scrumbled.

**Comment by mircobabini** [comment]
I can imagine this flow on url change detection.

**Ask user what's going on: changed url? staging site?**
IF no choice: nothing to do, just keep asking
IF changed url: update the current url
IF staging site: save the choice and activate staging mode

STAGING MODE means:
- additional settings page for staging with defaults turned on
- if wp5.7+ WP_ENVIRONMENT_TYPE should be in place = 'staging' (or at least != 'production')
- DISABLE_WP_CRON = true
- option to [disable all outgoing emails](https://wordpress.org/plugins/disable-emails)
- suggest to install toolkit and scramble data
- turn gateway(s) to sandbox
- disable crons (renewals reminder, expirations...) with a filter

**Comment by dparker1005** [comment]
Pausing crons after URL change was implemented in 2.10
