### ISSUE TITLE
The Generate Pages button appears if you change just one page setting to -none-.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#1104]
**Describe the bug**
If one page is not set on the settings page, the default Generate Pages button shows up. We should only show this if there are NO pages set at all.

**To Reproduce**
1. Generate Pages
2. Change the Checkout page to - none -
3. The Generate Pages button comes back.

**Expected behavior**
You should just see the list of pages with one page set to - none -.

We should change this check to use || instead of &&
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/functions.php#L2433-L2444

**Comment by kimcoleman** [comment]
I still think that the global $pmpro_pages_ready should only be "true" if they are complete - otherwise certain places in the site that rely on that check may return a false positive.

Could we instead update the return to send an array of set pages to check against OR just update the logic on the adminpages/pagesettings.php?
