### ISSUE TITLE
Settings Import/Export

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#1139]
**Is your feature request related to a problem? Please describe.**
Users want to be able to export settings from a staging site and import them into a live site.

Having a standard import/export format for settings would also make it possible to build wizards, CLI scripts, and other tools to update settings en mass.

**Describe the solution you'd like**

Add a data import/export section to the advanced settings page.

Show a list of all settings or types of settings (maybe just high level, like levels, discount codes, page settings, advanced settings, etc) that can be checked on/off to be included in the export. Clicking export gathers these settings and put them into a JSON format and generate a file to be downloaded.

The import tool would take a JSON file like that and use it to override the settings it finds.

THIS NEEDS TO HAVE AIR TIGHT SECURITY since it will be updating the options table. We need to allow list only certain settings to be updated.

There can be a checkbox to include "all settings prefixed with pmpro_" to make sure add on settings are included.

Links between pages and levels and categories and levels can be tricky because they are linked to post_ids and taxonomy_ids that might be different on the site being imported into. Maybe just note that this stuff can't be exported/imported in v1.

**Comment by dawgfather** [comment]
Jason asked that I provide some examples of current plugins that support these features:

I’m using these tools that support export and import through WP-CLI:
BeaverBuilder templates and the customizer export.
I’m using SmartSlider Templates.
I’m using WP Offload SES serialized settings (probably not an option for your solution) in WP-Config.
I’m using pricing-table-by-supsystic and exporting/importing my pricing tables.

The qualifier Jason used is  plugins that perform this “particularly well”. Beauty is in the eye of the beholder and everything can be improved, but the above are the best I can get at this moment.

**Comment by dawgfather** [comment]
ideadude - when you state - "Links between pages and levels and categories and levels can be tricky because they are linked to post_ids and taxonomy_ids that might be different on the site being imported into. Maybe just note that this stuff can't be exported/imported in v1." I would rather have that all and if I need to manually create a mapping table for each instance (dev, QA. prod) then I would rather do that. My first priority is being able to run developer builds without have to extract and import the whole database and the version manage those database extracts. The second is how to introduce changes in production without having to bring down production and rekey the changes tested in Dev and QA. The first should be easy the 2nd is much harder as you point out above. I've been exploring Versionpress but haven't taken a deep dive yet. Thanks for looking into this.

**Comment by ideadude** [comment]
We added this functionality into the PMPro Toolkit add on. You can find it there. https://github.com/strangerstudios/pmpro-toolkit/releases/tag/v0.7
