### ISSUE TITLE
BUG: Certain password characters in registration are being removed resulting different password

### ISSUE THREAD

**Issue by timvergara** [strangerstudios/paid-memberships-pro#1190]
**Describe the bug**
https://wordpress.org/support/topic/password-on-registration-doesnt-work/
Passwords with characters like "%54" are being removed, thus when a user registers passwords like "Dgfttr%54gs2" it becomes "Dgfttrgs2" which is a completely different password. This would result on invalid password when a user logs-in.  The main cause of the issue is the use of the function "sanitize_text_field" from the password fields which then removes any characters that are similiar to encoded characters.  

Note: Passwords mentioned above "Dgfttr%54gs2" works when I try it on WooCommerce or when I use the WP change password on edit account and it doesn't delete the characters like "%54"

**To Reproduce**
1. Go to 'http://pmprosingle.timstructures.com/membership-account/membership-levels/'
- You could try using your own installation if you like.
2. Select any plan 'Register and use password like: "Dgfttr%54gs2"'
3. After registration, Logout account
4. Login again using the password that you used.

**Screenshots**
No Screenshots needed

**Expected behavior**
A user should be able to login using the password that is used during registration.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.

WordPress 5.3
Paid Memberships Pro 2.2.2
PHP 7.3 (It happens on PHP 7.0, 7.1 or 7.2)
Theme: twenty nineteen
Plugin Active: ONLY Paid Memberships Pro
```
</details>

**Comment by ideadude** [comment]
Nice catch. Thanks for sharing.

We are sanitizing the password input here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/preheaders/checkout.php#L240-L251

But since we never echo the password, we shouldn't have to sanitize it. It seems like core WP doesn't sanitize it's password input either. https://github.com/WordPress/WordPress/blob/master/wp-login.php#L949-L955

We do sometimes store the password in session temporarily, e.g. when checking out with PayPal Express. I am not aware of any reason we need to have the password sanitized for that. There are security considerations due to having the password in session at all.

I think we can safely remove the sanitize_text_field calls here and anywhere else the password is pulled in.

Open to a PR for this.

**Comment by andrewlimaza** [comment]
Here's a related ticket - https://github.com/strangerstudios/paid-memberships-pro/issues/1026

**Comment by dparker1005** [comment]
Removing the sanitization call was implemented here: https://github.com/strangerstudios/paid-memberships-pro/commit/0505cd358f547feebd59ebdfea85411e71d74310
