### ISSUE TITLE
BUG: Users cannot update their Stripe payment info in PMPro

### ISSUE THREAD

**Issue by jayjay91** [strangerstudios/paid-memberships-pro#1197]
**Describe the bug**
Users cannot enter a new credit card number. Upon confirming, they are told to "fill out all the fields", even when every field is filled out. I have received numerous e-mails from subscribers and was able to reproduce this issue consistently. 

**To Reproduce**
1. Create subscription with Stripe gateway
2. Go to 'Update payment info' on the membership account page
2. Enter new credit card info
3. Click "Confirm"

**Expected behavior**
Update credit card info successfully.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
I use the newest versions of PM Pro and Wordpress.
</details>

**Comment by benholmen** [comment]
I ran into this same issue. I believe it is due to this commit: https://github.com/strangerstudios/paid-memberships-pro/commit/b0aa36170d580753947ec071232689ea1c931455

Before that commit, `pmpro_require_billing` was `undefined` on the Update Billing page. After the commit, it is `null`.

I was able to patch it on my install by modifying line 58 of js/pmpro-stripe.js:
`if ( typeof pmpro_require_billing === 'undefined' || pmpro_require_billing || pmpro_require_billing === null ) {`

This is not a permanent fix. I expect PMPro will release more comprehensive bugfix in the next release.

**Comment by jayjay91** [comment]
Cool, that solved it for me! Thank you.

**Comment by josheinstein** [comment]
This is affecting Braintree gateway as well.

**Comment by dparker1005** [comment]
This issue was addressed in PMPro v2.2.4 and v2.2.6.
