### ISSUE TITLE
Issue when wp_login_url is called too early.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#1383]
**Describe the bug**

If a plugin (for example the GoDaddy login mu-plugin) uses the login_url function too early, the following fatal error will be thrown:

> Fatal error: Uncaught Error: Call to a member function get_page_permastruct() on null in /var/www/staging/wp-includes/link-template.php:376

This is because we use the get_permalink() function here: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/login.php#L100

**To Reproduce**
1. Create a custom plugin that calls wp_login_url() before the wp_loaded hook has fired.

**Expected behavior**

We should filter the login URL without throwing an error.

**Proposed solution**

We could fix this in a couple of ways.

(1) Just bail and let the default login URL be used when trying to get it so early. We can check if `empty( $GLOBALS['wp_rewrite'] )` and if so return the default $login_url.

We could also wait until wp_loaded to set up the filter.

(2) Try to filter the URL without using the get_permalink function. One option would be to store the URL in a cached option or transient and pull the URL from there if it's early. We can set the transient when we're able to call get_permalink.

This feels like too much work/debt to add for this issue. I suggest just adding the filter on wp_loaded to avoid being called to early.

**Comment by kimcoleman** [comment]
Femi has a ticket about this right now and we are looking at a PR for core to get into next release. Would you like the entire function pmpro_login_url_filter to be moved like this:

`/**
 * Redirect to the login page for member login.
 * @since 2.3
 */
function pmpro_login_url_filter( $login_url='', $redirect='' ) {
	$login_page_id = pmpro_getOption( 'login_page_id' );
	if ( ! empty ( $login_page_id ) ) {
		$login_url = get_permalink( $login_page_id );
		
		if ( ! empty( $redirect ) ) {
			$login_url = add_query_arg( 'redirect_to', urlencode( $redirect ), $login_url ) ;
		}
	}

	return $login_url;
}

function pmpro_login_url_wp_loaded( )
	add_filter( 'login_url', 'pmpro_login_url_filter', 50, 2 );
add_action( 'wp_loaded', 'pmpro_login_url_wp_loaded' );
`

Or would we add this to another wp_loaded function in functions.php or elsewhere in plugin?
