### ISSUE TITLE
Undefined error when using the plugin in conjunction with Paid Memberships Pro - Register Helper Add On

### ISSUE THREAD

**Issue by Archie22is** [strangerstudios/paid-memberships-pro#1450]
**Describe the bug**
Undefined PHP function error when using the plugin in conjunction with Paid Memberships Pro - Register Helper Add On

**To Reproduce**
1. Update to 2.4.1
2. Install Paid Memberships Pro - Register Helper Add On 
3. Go to the registration page

**Error**
```
Uncaught Error: Call to undefined function pmpro_recaptcha_get_html() in /nas/content/live/theme-name/wp-content/plugins/pmpro-register-helper/shortcodes/pmpro_signup.php:116 Stack trace: #0 /nas/content/live/theme-name/wp-includes/shortcodes.php(343): pmprorh_signup_shortcode('', '', 'pmpro_signup') #1 [internal function]: do_shortcode_tag(Array) #2 /nas/content/live/theme-name/wp-includes/shortcodes.php(218): preg_replace_callback('/\\[(\\[?)(pmpro_...', 'do_shortcode_ta...', '[pmpro_signup]\n') #3 /nas/content/live/theme-name/wp-content/plugins/js_composer/include/helpers/helpers.php(236): do_shortcode('[pmpro_signup]\n') #4 /nas/content/live/theme-name/wp-content/plugins/js_composer/include/templates/shortcodes/vc_column_text.php(31): wpb_js_remove_wpautop('<p>[pmpro_signu...', true) #5 /nas/content/live/theme-name/wp-content/plugins/js_composer/include/classes/shortcodes/shortcodes.php(478): include('/nas/content/li...') #6 /nas/content/live/theme-name/wp-content/plugins/js_composer/include in /nas/content/live/theme-name/wp-content/plugins/pmpro-register-helper/shortcodes/pmpro_signup.php on line 116
```

**Expected behavior**
Spews and an undefined function error.

**WordPress Environment**
<details>
```
WordPress 5.5
Paid Membership Pro 2.4.1
Paid Memberships Pro - Register Helper Add On 1.6.1
```
</details>

**Comment by ideadude** [comment]
Thank you for the issue here, and sorry about the trouble it has caused.

We did recently tweak the code around the recaptcha. We previously loaded some of that code on every page load. That was causing issues with some caching systems and was just generally bad to load code we didn't need.

The new code tries to load if "pmpro_is_checkout" but that isn't true when using something like the signup shortcode.

The fix for this needs to be done in the RH and Sign Up Shortcode Add Ons. You can see those patches here:

https://github.com/strangerstudios/pmpro-register-helper/commit/5334c3a3dbdafb4943b72cd7180b9b1614d47e2b

and here:

https://github.com/strangerstudios/pmpro-signup-shortcode/commit/060153e11aa204ac119935f26850a509bdf15b99

I'm going to be pushing those out soon. They do fix the fatal error, but don't seem to actually apply the recaptcha at checkout (I'm testing with the invisible version). We may need a further update to get recaptcha working with the sign up shortcodes.

FYI - The version of the shortcode bundled with the Register Helper add on is deprecated. You should use the separate sign up shortcode add on here: https://www.paidmembershipspro.com/add-ons/pmpro-signup-shortcode/

We do try to keep the RH one bug free, but any new features/etc are only done in the separate add on.

**Comment by Archie22is** [comment]
Thank you. 
Apologies for the late reply @ideadude
