### ISSUE TITLE
Feature Request: Referral Program

### ISSUE THREAD

**Issue by hbcondo** [strangerstudios/paid-memberships-pro#1479]
**Is your feature request related to a problem? Please describe.**
Currently PMP does not offer or integrate with a referral program that gives each customer a unique referral link and reward for successful referrals.

**Describe the solution you'd like**
Please integrate with a [referral program plugin](https://wordpress.org/plugins/search/referral/) so PMP sites can incentivize their customers in bringing in new customers. Incentives are often a one-time discount, gift card, or a plan upgrade.

**Describe alternatives you've considered**
Upgrade existing [Affiliates plugin](https://www.paidmembershipspro.com/add-ons/pmpro-lightweight-affiliate-tracking/) to perform payouts to affiliates

**Additional context**

> _People influence people. Nothing influences people more than a recommendation from a trusted friend. A trusted referral is the holy grail of advertising_ - Mark Zuckerberg

**Comment by dparker1005** [comment]
Hi @hbcondo,

We have an article here on a couple of affiliate WordPress plugins which integrate with Paid Memberships Pro:
https://www.paidmembershipspro.com/other-third-party-integrations-and-plugins/affiliate/

**Comment by hbcondo** [comment]
<a href="https://www.referralcandy.com/blog/referral-vs-affiliate-marketing-whats-the-difference-infographic/"><img src="http://cdn.referralcandy.com/images/referral-affiliate-difference-by-referralcandy-590.png" alt="Referral vs Affiliate Marketing: What's the difference? [Infographic]" title="Referral vs Affiliate Marketing: What's the difference? [Infographic]" width="590" /></a><br /><a href="http://referralcandy.wpengine.com">ReferralCandy - Refer-a-friend Program for Ecommerce Stores</a>

**Comment by dparker1005** [comment]
Hi @hbcondo,

I apologize that none of the plugins listed that article will fit your needs. We are aware that affiliates and referrals are not the same thing, but I linked to that article as that is the closest functionality that is currently available to your desired functionality and because you recommended that we update our Affiliates Add On to support this use-case.

I am changing the labels of this ticket to instead be a new plugin request; however, this is not currently on the development schedule for PMPro. If this is a feature that is necessary on your site, this will require custom development to implement.

**Comment by ideadude** [comment]
Neat comic.

Pausing subscriptions or giving users credits is something that is handled (if even possible) very differently with each gateway. Further, I find these referral programs rarely "just work" and require a lot of effort to be effective... both marketing efforts and development efforts to make sure the process is as smooth as possible for the specific site.

For these reasons, I don't see us every working on this ourselves. If someone finds a third party plugin or service that does this well, feel free to comment.
