### ISSUE TITLE
Prepopulating checkout fields from $_SESSION

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/paid-memberships-pro#1496]
**Problem**
If a user checks out with PayPal Express, PMPro stores their PMPro checkout information in a $_SESSION variable when the user is sent to PayPal Express to pay. If the user then exits the PayPal checkout before completing the payment and goes back to the PMPro checkout page, some of the information will be prepopulated from $_SESSION, but some won't (mainly the username, email, and password fields) even though that information is available in $_SESSION.

**Possible Solutions**
There are two approaches to make this behavior more consistent:
1. Prepopulate all fields (besides password) from $_SESSION when possible
2. Detect when a user leaves the PayPal payment process and clear $_SESSION as a security measure

Approach 1 is pretty straightforward and would just require some tweaks when building the checkout page, but approach 2 seems to protect user information better (instead of having a desired password floating around in $_SESSION). @ideadude's suggestion for approach 2 is to `change the “cancel” URL in PayPal to add a param to tell PMPro to clear the session caches`, though this wouldn't catch cases where users just leave the checkout page or close the tab.

We also should consider updating Register Helper based on the approach we decide to take here.

**Temporary Workarounds**
We have gists here to prepopulate additional fields at checkout and prepopulate no fields respectively:
- https://gist.github.com/kimwhite/0c2f9828b3980acdc15e38739f662f02#file-my-pmpro-custom-autofill-checkout-php
- https://gist.github.com/kimwhite/e53bbf539f9a7639e5ca70c8d19d02fd#file-clear-checkout-page-variables-php

**Comment by tictag** [comment]
**FOR MODS ONLY** further information in ticket: https://www.paidmembershipspro.com/forums/topic/bug-pmpro-core-inconsistent-cached-data-part-2/ and originally: https://www.paidmembershipspro.com/forums/topic/bug-pmpro-core-inconsistent-cached-data-when-returning-from-external-gateway/, which includes a video screencast of the issue.

**Comment by tictag** [comment]
Regarding passwords...

I note above, "_Prepopulate all fields (besides password)..._" but I don't see any reason not store the password:

1. The user has entered this password freely
2. The user will only have to re-enter it if it is not pre-populated (on return) ... and if they don't or miss the fact that it is missing, they will consequently receive a form validation error
3. The user would not have arrived at the checkout page without first agreeing to the website's / organisation's privacy policy (_explicitly or more likely implicitly_)
4. Other websites / registration forms (_somehow_) cache the password

Maybe there is reason to hash the password prior to storing it in $_SESSION but as this must be done anyway to store in the WordPress database, this can't be that difficult to do (_I genuinely don't know what's involved in hashing a password!_).

What I am finding is that there is a direct correlation between 'faff' at the checkout and receipt of membership fees: more 'faff' = fewer receipts. Having to re-enter information the user has already entered is 'faff'. I know this because I have been told this on multiple occasions now (_we check on Orders that do not complete via PayPal_).

Please consider caching the password i.e. in addition to all the other fields.

**Comment by mircobabini** [comment]
I think that the PayPal Express gateway has a lot of issues as reported #1341 and #1338.

Also, I want to add a new one:
1) Logged user on the site, goes into checkout and get redirected to paypal
2) Lose its section (i.e. logs out) in some way, multiple tabs and so on
3) After paypal processed the payment the user gets back to the site and... error: email already exists

This is because the checkout is trying to create the user, since he is not logged in anymore.
Obviously the customers contact us and the say "yeah, I know it already exists... it's ME!"

Also, this situation must be manually managed on site to fix everything. 
In this case, to ensure the process won't stop, if the user is not logged in but the emails exists (when get back from paypal) I just use the existing user and automatically sign in the user again. I assume he lost the session during the proccess.

Don't know about security implication here.

**Comment by tictag** [comment]
Would it be possible to 'popout' the PayPal Express page so that the checkout page remains 'intact', so to speak? Or use a modal form to contain the PayPal Express page? This way there would be no need to 'leave' the checkout page, so no need to store/retrieve anything.

I've certainly seen the 'popout' method used on other checkouts e.g. vampirevape.co.uk.

This would also prevent having to store/retrieve the password field.

Care would need to be taken in how the 'calling' page i.e. checkout, responded to the 'popout' page i.e. success/failure/cancel etc.

**Comment by dparker1005** [comment]
Closing as PayPal Express no longer stores data in session. Information is now stored in order meta.
