### ISSUE TITLE
Subscription delay wording is incorrect when setting an initial payment amount equal to subscription.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/paid-memberships-pro#1544]
**Describe the bug**
When setting up a Level or Discount code and using Subscription Delay, if the amount is the same, the line "is $$$ now and then" is removed.

The price for membership is $4.00 now and then $5.00 per Year after your 200 day trial.

but if both are $5 we get this:

The price for membership is $5.00 per Year after your 200 day trial.
![image](https://user-images.githubusercontent.com/8083630/103704637-9ab22200-4f77-11eb-820f-312508f8cace.png)
![image](https://user-images.githubusercontent.com/8083630/103704770-d1883800-4f77-11eb-8c45-ab54d37ea350.png)

**Expected behavior**
Should show the initial price.

**Comment by michaelbeil** [comment]
I opened a similar issue in the Subscription Delays Add On repo: https://github.com/strangerstudios/pmpro-subscription-delays/issues/25. Could add the above information there, so it can be addressed in the future.

**Comment by kimwhite** [comment]
My bad. Yes, this should be on plugin.

**Comment by dparker1005** [comment]
This is the expected behavior of PMPro. If the initial payment and billing amount match, then they will not be separated in the level cost.

For reference, here is the code that does that:
https://github.com/strangerstudios/paid-memberships-pro/blob/dfbce960f59ba418e0ee5d2dc4b966001f3a6bcc/includes/functions.php#L404-L417
