### ISSUE TITLE
PHP Notice on plugin activation

### ISSUE THREAD

**Issue by amdrew** [strangerstudios/paid-memberships-pro#213]
At soon as I activate the plugin on a fresh install this notice is outputted about 18 times:

```
PHP Notice:  Undefined offset: 1 in /wordpress/wp-admin/includes/upgrade.php on line 1986
```

WordPress 4.2.2
PMP: 1.8.4.1

**Comment by strangerstudios** [comment]
Looks like a dbDelta issue. We need to figure out which SQL it's complaining about (with 18, it might be all of them) and fix it up.

The Codex has some suggestions like not using backticks that we aren't following 100%.

http://codex.wordpress.org/Creating_Tables_with_Plugins

* You must put each field on its own line in your SQL statement.
* You must have two spaces between the words PRIMARY KEY and the definition of your primary key.
* You must use the key word KEY rather than its synonym INDEX and you must include at least one KEY.
* You must not use any apostrophes or backticks around field names.
* Field types must be all lowercase.
* SQL keywords, like CREATE TABLE and UPDATE, must be uppercase.
* You must specify the length of all field that accept a length parameter. int(11), for example.

We can update the create table queries and try again. Thanks for the heads up on this.
