### ISSUE TITLE
Submit button improvements

### ISSUE THREAD

**Issue by amdrew** [strangerstudios/paid-memberships-pro#218]
The `Submit and check out` button seems to have a margin-left of 130px, which makes it look strangely placed:

![screen shot 2015-05-22 at 2 18 21 pm](https://cloud.githubusercontent.com/assets/52581/7762915/6d7af1ca-008d-11e5-9d19-cd32532e40f2.png)

Is there a reason for the 130px that I'm not seeing? I propose removing this so it's nicely aligned to the left:

![screen shot 2015-05-22 at 2 19 33 pm](https://cloud.githubusercontent.com/assets/52581/7762926/95bd9a16-008d-11e5-9449-7e1c61c25992.png)

**Comment by strangerstudios** [comment]
The 130px is the same as the label width. When the labels are styled to show up to the left of the fields instead of on top, this makes the button line up with the form fields instead of the form labels.

So something like:
`
username:   [        ]
password:    [        ]
                    [submit]
`

Instead of
`
username:   [        ]
password:    [        ]
[submit]
`

When the fields are shown above like your theme seems to be doing (although having other issues I think), it probably makes sense to move the submit button further to the left like that.

You can override the PMPro css by placing a file in your theme folder or by using other CSS that overrides it.

I am open to changing the default, but we tried to style things to work well in the default WP themes. We can change things going forward, but it's a little tricky since a lot of folks are expecting the CSS to be the way it is now and rely on the quarks.

**Comment by sumobi** [comment]
Ahh of course, didn't see that initially. Thanks for the explanation. You're right, very hard to change things once they've been a certain way for a while. Feel free to close!

**Comment by strangerstudios** [comment]
I'm going to leave these open for a bit. Kim our designer is going to be looking into supporting 2015 without breaking things too badly for anyone else.

**Comment by kimcoleman** [comment]
Also improved in the current plugin version with table-free forms. See demo:

http://demo.paidmembershipspro.com/twentyfifteen/membership-account/membership-checkout/?level=2
