### ISSUE TITLE
PmPRO initial purchase browser session_id get cancelled with same session _id by means of automation and not user input

### ISSUE THREAD

**Issue by jacothiart** [strangerstudios/paid-memberships-pro#2336]
Hi PmPRO

We have initial purchases of a year ago, dating that some of our users only, 4 of them, membership level get cancelled automatically after they make a payment with the same session_id(browser session) they are using to purchase the membership level

We understand that with automation, the session_id is empty, and by means of user input the session_id is not empty

With top mentioned cancellation, happening in a timespan of 5 - 30 minutes after an initial membership purchase with the same session_id in both "active" and "cancelled" database entries, making 2 database entries in the database.

Further more, every year, the length of the membership expires, and with these 2 membership levels from the root cause, of an initial purchase being cancelled 5 to 30 minutes straight after initial purchase of a membership level, the payments gets deducted twice by third party payment gateway Stripe, which is correct, on each expiry of 4 of our users because of this root cause.

We have confirmation that the user is not cancelling their initial payment for membership subscription afterwards, with this in mind the database entry does specify the same browser session token.

Could this be something that was fixed prior to the latest version of PmPRO, if you can let us know of such an fix in the changelog of PmPRO, during the course dating 2 years back of PmPRO plugins till now?

Kind Regards,

Jaco

**Comment by andrewlimaza** [comment]
Hi Jaco,

Thank you for reaching out and creating the issue here, we don't actively look at the issues in Github for support related requests.

We can only think of v2.9.5 had some Stripe updates included in this release to help you debug Stripe - https://www.paidmembershipspro.com/pmpro-update-2-9-5/ It's not exactly what you're describing here, but figured it might give some insight into recent changes around Stripe.

However, we're eager to assist you with this but will need more information as it doesn't seem like a common issue we've encountered. Would you mind reaching out to our support team on www.paidmembershipspro.com/support to provide more sensitive information about your PMPro site and configuration?
