### ISSUE TITLE
Page Shortcodes are not working any longer. 

### ISSUE THREAD

**Issue by BernardHenryManning** [strangerstudios/paid-memberships-pro#241]
After updating to 1.8.5.5 the shortcodes for pages no longer function.

**Comment by terminalpixel** [comment]
Same issue here.

1.7.4 seems to be the most recent version where the `[pmpro_levels]` shortcode works for me.

**Comment by strangerstudios** [comment]
I'm going to close this because we haven't heard anything about this in a while. I am not sure what might have caused this. Some themes and page builders will cause conflicts with this, and they are often updated at the same time PMPro is and might be what happened here.

If anyone runs into this again and has more information on how to recreate the issue, please open a new issue. Thanks.

**Comment by bsha100** [comment]
I'm having the same problem. I've tried with different themes, and disabled all other plugins. I'm able to use other shortcodes, but PMPro's don't work. They just echo the shortcode itself (i.e. [pmpro_levels] ). Whatever is happening, it's behaving as if the  page shortcodes aren't being registered. I looked in the shortcodes directory, and searched through a few of the files, but couldn't find anything that registers those shortcodes. What's most frustrating is that there are no errors being generated, and there is only the most basic information on the PMPro site. There was mention that some themes can interfere with the plugin, can you elaborate on that?

**Comment by SteveShengStar** [comment]
Experiencing the Same Issue here.

**Comment by bsha100** [comment]
So, a few things that I noticed was that if I use <?php echo do_shortcode('[pmpro_levels]'); ?> in a template, there is no hope of getting it to work. I was able to get it working by creating a template that I stripped everything out of except the Wordpress header, loop, and footer calls, with the header stripped of most of the scripts that I didn't need for the PMPro pages.

 I found that if I deleted all of the pages, and the post_meta entries for the PMPro pages, the 'let us generate the pages for you' link came back up, and it generated the pages with **/membership-accounts/** as the parent of the other pages, so that might help, depending on how your permalink structure is setup.
