### ISSUE TITLE
billing country not passed on to stripe via API 

### ISSUE THREAD

**Issue by ainhoaborobia** [strangerstudios/paid-memberships-pro#2600]
I m facing problems when clients pay for my membership at https://escuelaumauma.com. I have reviewed all configuration and everything seems fine and I dont see any errors but my clients are unable to pay through webhoook and get an error message: "You passed an empty string for 'biling_details[address][country]'. We assume empty values are an attempt to unset a parameter; however 'billing_details[address][country]"cannot be unset. You should remove 'billing_details[address][country]' from you request or supply a nen-empty value". The problem is clients claim they fill out all the details. I cloned several months ago my website to another server but configuration is the same. Contacted stripe support and told me billing country information is not reaching stripe hence the error. Any help?

We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://www.paidmembershipspro.com/documentation/

**Technical support for premium extensions or if you're an active paid member**
Submit a ticket on our helpdesk by visiting https://www.paidmembershipspro.com/new-topic/ (Please note that an [active paid membership](https://www.paidmembershipspro.com/pricing) is required for paid support.)

**General usage and development questions**
- WordPress.org Forums: https://wordpress.org/support/plugin/paid-memberships-pro
- Website: https://www.paidmembershipspro.com/contact/

**Comment by julesgamble** [comment]
Dude. Just move to Shopify and use the Seal Subscriptions app. WordPress is not inherently built for e-commerce. Sure, it’s got plugins that can turn your CMS into an e-commerce platform with Woocommerce and subscription plugins. But why reinvent the wheel? I gave up on getting this subscription app to suit my needs. Most people that shop small business know Shopify and trust those sites. I converted my entire Wordpress website into a Shopify online store. No regrets. Less headaches. No hopping on GitHub for answers. So much better!Sent from my iPhoneOn Aug 26, 2023, at 5:55 PM, ainhoaborobia ***@***.***> wrote:﻿
I m facing problems when clients pay for my membership at https://escuelaumauma.com. I have reviewed all configuration and everything seems fine and I dont see any errors but my clients are unable to pay through webhoook and get an error message: "You passed an empty string for 'biling_details[address][country]'. We assume empty values are an attempt to unset a parameter; however 'billing_details[address][country]"cannot be unset. You should remove 'billing_details[address][country]' from you request or supply a nen-empty value". The problem is clients claim they fill out all the details. I cloned several months ago my website to another server but configuration is the same. Contacted stripe support and told me billing country information is not reaching stripe hence the error. Any help?
We don't offer technical support on GitHub so we recommend using the following:
Reading our documentation
Usage docs can be found here: https://www.paidmembershipspro.com/documentation/
Technical support for premium extensions or if you're an active paid member
Submit a ticket on our helpdesk by visiting https://www.paidmembershipspro.com/new-topic/ (Please note that an active paid membership is required for paid support.)
General usage and development questions

WordPress.org Forums: https://wordpress.org/support/plugin/paid-memberships-pro
Website: https://www.paidmembershipspro.com/contact/

**Comment by andrewlimaza** [comment]
Hi @ainhoaborobia 

I'm sorry to hear about this issue you are facing with Stripe. Are you still facing this issue after updating? If so, would you mind opening up a support ticket on our site if you haven't done so already?

I haven't been able to replicate this issue on my own site.

**Comment by andrewlimaza** [comment]
If you still need assistance, please can you open a support ticket here and someone from our team will continue to assist you - https://www.paidmembershipspro.com/new-topic/
