### ISSUE TITLE
Monthly Report vs. Last 12 Months Showing Different Data

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#2691]
**Describe the bug**
The monthly revenue report shows data for all months in the selected year.

You can also show a leading 12 months of data. In this view, the report data for the "oldest" month is incorrect as shown in the screenshots below:

**Screenshots**
![Screenshot 2023-11-28 at 7 38 02 AM](https://github.com/strangerstudios/paid-memberships-pro/assets/5312875/b97467b4-c7a1-406b-a38f-cd15f3933434)

![Screenshot 2023-11-28 at 7 38 15 AM](https://github.com/strangerstudios/paid-memberships-pro/assets/5312875/a382a679-b5b7-4556-8bb5-1da4befa0c37)

**Expected behavior**
The month "November" in both screenshots should show the same data.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by MaximilianoRicoTabo** [comment]
I was playing with this one and I'm not really sure how should we proceed here. I was able to reproduce but with January in my case. Basically the issue is that "Last 12 months" report takes from today and 12 months back in the past which at the end of the day makes that you have 11 full month in the middle and two partials in the edges. Then, when you compare monthly revenue with last 12 months they don't match, because the comparison is a full month agains a partial. Does it makes sense ? Should we fix ? Should we avoid partials ? Please need feedback re business rules here. Thanks @kimcoleman @andrewlimaza
