### ISSUE TITLE
pmpro_changeMembershipLevel ommited advanced membership setting

### ISSUE THREAD

**Issue by vlapo** [strangerstudios/paid-memberships-pro#397]
Hi, 

I use pmpro_changeMembershipLevel with level id as first parameter. Membership changed correctly to level with this id but I dont see any advanced settings of membership. 

There are membership settings:
![image](https://cloud.githubusercontent.com/assets/2484063/20316152/0485e244-ab61-11e6-8641-7b03f9983124.png)

But here is my mysql row in database after change to mentioned membership level:
![image](https://cloud.githubusercontent.com/assets/2484063/20316212/460d247a-ab61-11e6-9e5a-4f6476ed7ded.png)

Is this correct behavior? I use admin to change between levels when user requests. And after I change it users have free premium memberships on my webpage.

**Comment by strangerstudios** [comment]
This is by design. Calling pmpro_changeMembershipLevel assume a free pro-bono membership vs using the pricing in the DB.

You can pass an array to the function and the values from the array will be used to set the prices/etc.

Here is an example that would do that and set the values per the DB:
https://gist.github.com/strangerstudios/d2e50c63ac9c1647d6bc
