### ISSUE TITLE
Membership Checkout Popup for CCV "Whats This" reveals full file path

### ISSUE THREAD

**Issue by jbruggeling** [strangerstudios/paid-memberships-pro#428]
When a end user clicks the whats this hyperlink on the checkout screen next to the ccv they get the full file path to the html file on the server. Ie www.yourdomain.com/wp-content/plugins/paid-memberships-pro/pages/popup-cvv.html

Can this be changed to a relative path

**Comment by strangerstudios** [comment]
There are better ways to do this these days. I'll see if we can address it. I would be open to a pull request that updated this to just load through an admin-ajax.php request. I wouldn't want to include a popover JS library or rely on one in the WP admin. It would be nice to have the output of this as a PHP var string that could be translated as well vs a .html file. Not sure if anyone translates that file in the included translations.

**Comment by strangerstudios** [comment]
Perhaps we should use the username_exists function instead of get_user_by here:
https://github.com/strangerstudios/paid-memberships-pro/blob/dev/preheaders/checkout.php#L358

I feel like there were some recent pull requests around this as well. I'm open to a pull request that tightens up the checks in preheader/checkout.php

**Comment by jbruggeling** [comment]
Any update on getting this fixed?

**Comment by dparker1005** [comment]
This popup was removed in PMPro v2.10
