### ISSUE TITLE
Stripe cancellation sometimes fails

### ISSUE THREAD

**Issue by Ninjami-Juho** [strangerstudios/paid-memberships-pro#433]
After a update of PMPRO in January, looks like Stripe sometimes fails to cancel subscription after set number of failed payment attempts. Mostly seems to work and in those cases the webhook (customer.subscription.deleted) response is: 

`This user has a different level than the one associated with this order. Their membership was probably changed by an admin or through an upgrade/downgrade. (Order #xxx, Subscription Transaction ID #sub_xxx)Subscription deleted for user ID #xxx. Event ID #evt_xxx.`

and when it fails, the webhook responds with:

`We've already processed this cancellation. Probably originated from WP/PMPro. (Order #xxx, Subscription Transaction ID #sub_xxx)Subscription deleted for user ID #xxx. Event ID #evt_xxx.`

Thought I can see in the webhook that source is "automatic" in both cases and not api (WP/PMPro).

**Comment by dparker1005** [comment]
Our Stripe integration was overhauled in the 2.1 SCA update and has had additional updates to improve reliability since then. Is this an issue that you are still seeing on your site? If so, can you please confirm that the user's membership level when the webhook is received is the same membership level present in their most recent PMPro order?

**Comment by dparker1005** [comment]
Closing as this issue no longer appears to be happening.
