### ISSUE TITLE
Fatal error in sendInvoiceEmail from getDiscountCode

### ISSUE THREAD

**Issue by bwsolutions** [strangerstudios/paid-memberships-pro#447]
In sendInvoiceEmail there is a call to getDiscountCode(), if there is a discount code associated with this invoice then getDiscountCode returns an Object/Row with discount code info. 

However, sendInvoiceEmail expects this to be a string to be used in the email message.

This causes a Fatal Error.
Not sure if sendInvoiceEmail needs to be changed to expect the Object/Row or if getDiscountCode should be changed to just return the string????

**Comment by strangerstudios** [comment]
I believe this commit will fix this:
https://github.com/strangerstudios/paid-memberships-pro/commit/13c40aeb5ee022cc64ee8aede88048bc80f358d5

Some notes: The $order->discount_code value is set to a string during preheaders/checkout.php, but you are correct that the getDiscountCode method returns an object if nothing is already set in ->discount_code. The sendInvoiceEmail method is typically called during preheaders/checkout.php and so this was fine, but I think with gateways like PayPalExpress, it might be called with ->discount_code being set to an object.

There might be a better long term fix here, where we have the getDiscountCode() method forced to return an object and/or update the checkout code to set that value to an object instead of a string, but I'm worried for now about breaking other code that might expect that string. This commit should fix the immediate issue, and we'll look to a better long term fix.

Thanks!
