### ISSUE TITLE
Disable PMPRO redirection

### ISSUE THREAD

**Issue by ravimartins** [strangerstudios/paid-memberships-pro#449]
Guys, how can i disable PMPRO page redirection when users that aren't members login on my website? I'm getting crazy because i can't find it.

**Comment by eighty20results** [comment]
We will always redirect away from a protected page/post (that's why PMPro is installed, isn't it? To protect content). 

A post/page can be protected with the "Require Membership" checkboxes, or because a post category has been selected as belonging to a membership level.

Beyond that, I don't really know what you're asking, unfortunately (I'm not understanding the question, possibly).

**Comment by ravimartins** [comment]
I would like to disable the login redirection to acquire plan when users aren't members. I have a website that are a mix of e-commerce and membership, so many times i will have users that aren't members.

**Comment by eighty20results** [comment]
Then don't protect the page/post... 

We only redirect the PMPro account management pages (Account, Billing Info, Invoice, etc). Any page where you've explicitly configured PMPro to protect the page, we will show the "Access denied, please log in or upgrade your membership" message. If the site redirects when a protected page is shown, it's because you have custom code somewhere to do so.

**Comment by strangerstudios** [comment]
Just replied here as well (https://github.com/strangerstudios/paid-memberships-pro/issues/446#issuecomment-299944614)

> Here's where we add the login redirect.
> 
> https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/login.php#L37
> 
> This code will disable it if run on init:
> 
>     remove_filter('login_redirect','pmpro_login_redirect', 10, 3);
> 
> I'll think if it makes sense to add a setting to adjust how this works.

**Comment by cwestfall9** [comment]
Having trouble with the BILLING page constantly redirecting to the levels page, I see that the above statement, **"We only redirect the PMPro account management pages (Account, Billing Info, Invoice, etc).**" is not shown in the code, where only the "checkout" page is protected against redirect.

Sure would like to have these other page protected against redirecting. Finding that if the user is logged in, no problem - the (change) billing page loads fine. If not logged in, however, the billing page redirects to the "levels" page to sign up all over again. This has been resulting in users that wish to change their billling information thinking that this is the way to do it, and signing up all over again.

"		}
		elseif(strpos($redirect_to, "checkout") !==  false)
		{
			//if the redirect url includes the word checkout, leave it alone"
From: login.php
Reference: https://www.paidmembershipspro.com/hook/pmpro_login_redirect/#more-9274
