### ISSUE TITLE
String "Are you sure you want to cancel your ... membership?" not being translated

### ISSUE THREAD

**Issue by accessallareas** [strangerstudios/paid-memberships-pro#465]
Are you sure you want to cancel your %s membership? is not part of the translation file.

**Comment by andrewlimaza** [comment]
hey @accessallareas 

I'm sorry to hear about the issue you are facing.

Would you mind telling me which language you are trying to translate this into so I may recreate the issue on my local environment?

For some more information regarding this, you may follow this guide to create a new language file which may generate the string into the file - https://www.paidmembershipspro.com/documentation/languages/create-a-new-translation/

I look forward to hearing from you, please feel free to post this on www.paidmembershipspro.com

**Comment by strangerstudios** [comment]
Our script that generates the .pot file for PMPro doesn't support the _n() string translation function, which is used on that string. Now that we have GlotPress support, I believe you can find that string in GlotPress and if the language has 80%+ coverage that translation will be used instead of the one we are bundling.

I'd rather wait for GlotPress get caught up to speed than update our code or mess with our old .pot generation script. But if this is still a problem in a month or so, I'll take another look.

Thanks.

**Comment by accessallareas** [comment]
Thanks for the info.
