### ISSUE TITLE
Field AUTOBILLAMT should be AUTOBILLOUTAMT

### ISSUE THREAD

**Issue by jubstuff** [strangerstudios/paid-memberships-pro#51]
As I was reading the documentation for [Recurring Payments with PayPal](https://cms.paypal.com/it/cgi-bin/?cmd=_render-content&content_ID=developer/e_howto_api_WPRecurringPayments#id086520F027U__id08652600QAX), it seems that the field AUTOBILLAMT should be named AUTOBILLOUTAMT.

For example it's used in the [PayPal Express Gateway](https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_paypalexpress.php#L50)

**Comment by strangerstudios** [comment]
Wow. Nice catch... 3 years ago. I overlooked this and I guess it never really came up because that setting only applies to cases where payments fail and usually a retry of the payment goes through or the account is cancelled before the next payment.

Still it makes sense to have this set correctly. Fixing now.

**Comment by iinkov** [comment]
I see you don't support backwards compatibility as you just can change the name. What if someone use old one?
