### ISSUE TITLE
Save TOS accepted date somewhere.

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/paid-memberships-pro#530]
Something like this:
https://gist.github.com/strangerstudios/9331183

Think about saving to order notes instead and/or save to user meta in a data structure that saves each time they check the TOS box.

array(
  array('date'=>$timestamp, 'ip'=>$remote_addr, 'order_id'=>$order_id),
  ...
)

**Comment by eighty20results** [comment]
For this to make sense (be applicable as a legally valid means of tracking acceptance of the ToS), it will need to do more than simply track the fact that somebody clicked the checkbox. 

Not a lawyer, but from my corporate days, I recall it also needs to ask for positive confirmation of receipt of the ToS.

A checkbox isn't enough, it has to be "signed" and agreed to, using one of the legally accepted electronic signature options and in the context of the ToS text. Thus it can't use the supplied user email from the email field as a "signature". Also can't use IP address either since the IP address is by no means not unique to the user who agreed. 

Then it has to be stored somewhere with a clear audit trail associated with it. 

Adding a timestamp and/or IP address is not going to cut it in a dispute. Not even close, unfortunately.

**Comment by andrewlimaza** [comment]
I've never received a confirmation by clicking agreeing to Terms and Conditions when checking out for a website?

Apparently, it's good enough that with the following (paraphrasing here):

* The TOS is easily accessible at any time and the user can print it at any time.
* If the user is forced to scroll down to the end of the TOS page before checking out, that's really good too.

**Comment by ideadude** [comment]
GDPR discussions have given us reason to revisit this. We need to at the very least track that the TOS was checked at checkout either in the order data or in user meta... with a timestamp and the page that was agreed to.

Ideally:
* we keep track of every such time that users check the box and submit.
* prompt users to agree again if we don't have data for their checking or the TOS has changed
* allow for other types of agreements besides the TOS

**Comment by ideadude** [comment]
We now save the date of consent into a user meta option at checkout. But we still need to ask for new consent and update it when the TOS is updated. Following up discussion of that here https://github.com/strangerstudios/paid-memberships-pro/issues/723
