### ISSUE TITLE
PMP breaks 'post__not_in' parameter in WP Query

### ISSUE THREAD

**Issue by bradley2083** [strangerstudios/paid-memberships-pro#600]
In testing with just the default theme and no other plugins, a custom secondary query using WP Query at the end of my single.php template to show a few other posts (related posts/pagination of sorts) does not exclude the current page ID when adding 'post__not_in' => (get_the_ID()) to the arguments.  However, with PMP deactivated, the query works properly.

**Comment by ideadude** [comment]
Should be fixed in this commit now https://github.com/strangerstudios/paid-memberships-pro/commit/179f556ecb4ad8ec004f99d885c8a2ba8adf3aa1

Double check if queries are cached if testing. Please open a new issue if you're still having trouble after using that patch or updating to the next release, which will include that. Thanks.
