### ISSUE TITLE
Bad path to wp-load.php

### ISSUE THREAD

**Issue by chrisvanpatten** [strangerstudios/paid-memberships-pro#61]
```php
Warning: require_once(/home/content/67/10323067/html/content/plugins/paid-memberships-pro/services/../../../../wp-load.php) [function.require-once]: failed to open stream: No such file or directory in /home/content/67/10323067/html/content/plugins/paid-memberships-pro/services/applydiscountcode.php on line 9

Fatal error: require_once() [function.require]: Failed opening required '/home/content/67/10323067/html/content/plugins/paid-memberships-pro/services/../../../../wp-load.php' (include_path='.:/usr/local/php5_3/lib/php') in /home/content/67/10323067/html/content/plugins/paid-memberships-pro/services/applydiscountcode.php on line 9
```

We keep `wp-load.php` at `site.com/wp/wp-load.php`, not `site.com/wp-load.php`, as part of our [wpframe](https://github.com/vanpattenmedia/wpframe) setup, so the relative path you use here doesn't work properly.

**Comment by retlehs** [comment]
yep, still an issue. any install that has wordpress in a subdirectory is broken.

https://github.com/strangerstudios/paid-memberships-pro/search?utf8=%E2%9C%93&q=wp-load

ref: http://ottopress.com/2010/dont-include-wp-load-please/

**Comment by kalenjohnson** [comment]
I've run into a very strange issue after having successfully gotten PMPro set up on a site with WP in a sub-directory.

As soon as I added discount codes to checkout, I was getting a popup with "Error applying discount". Following the trail, discount codes make an AJAX call to admin-ajax.php: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/checkout.php#L136

Which loads services/applydiscountcode.php: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/services.php#L8-L16

I'm pretty sure that admin-ajax.php calls does NOT set `WP_USE_THEMES`: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/services/applydiscountcode.php#L6-L10

So because of that, wp-load.php is trying to be loaded. Which is already included in admin-ajax.php, but since it's a missing file if WP is installed in a sub-directory, it always errors.

Not sure of the best fix for this. Perhaps each of these "service" php files should also check for `DOING_AJAX` ?

**Comment by strangerstudios** [comment]
Cleaning up old issues. Thanks again @mathieuhays for fixing this here https://github.com/strangerstudios/paid-memberships-pro/issues/264

If anyone is still having related issues here, please open a new issue. Thanks.
