### ISSUE TITLE
Move checkout.php JavaScript into .js files

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/paid-memberships-pro#803]
The checkout page template and gateway classes add a lot of inline JS code. These can break if other inline JS are broken and also can't be bundled and delivered in an optimized way for caching/etc.

We should move all JS out of the checkout.php template and into a JS file with the appropriate values setup via localization instead of inline php tags.

Some consideration should be done so existing templates continue to work. (Needs thought)

**Comment by pbrocks** [comment]
@ideadude Looks like some files on Dev changed before I got to my PR, but here is what I have so far:
https://github.com/strangerstudios/paid-memberships-pro/compare/dev...pbrocks:dev-checkout-js

While pulling the js out, I wanted to ask about/suggest some things.

[Here is a screencast](https://monosnap.com/file/0G0dbpdjXWLx3YCFfGUtRooQphvMxU)
![checkout-page-enqueued-js](https://user-images.githubusercontent.com/5721313/49163579-66c99480-f2fb-11e8-8ed0-8114956cd757.gif)

Can I get your thoughts on this?

**Comment by pbrocks** [comment]
User flow:

- User selects a level
- Taken to checkout page
- Other Discount code input, but no button shown
- Discount code hidden under payment
- User inputs Other discount code, button shows, Discount code under payment shows too

I also added a filter for the AJAX timeout, but I'm not sure if that's even needed.
For the what's this, I went with a modal, rather than a window. Is that too much of a departure from existing?

**Comment by pbrocks** [comment]
I pulled Dev again and merged. Didn't appear to be any conflicts, so hopefully this branch is better for you. [https://github.com/strangerstudios/paid-memberships-pro/compare/dev...pbrocks:dev-update-ckout-js](https://github.com/strangerstudios/paid-memberships-pro/compare/dev...pbrocks:dev-update-ckout-js)
