### ISSUE TITLE
Stop gateway communications when changing environment to "Testing"

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/paid-memberships-pro#816]
This is feedback from a user support ticket on Paid Memberships Pro. The user had set up a development site and set the gateway to "Sandbox/Testing" but did not update the API keys to the Stripe testing API keys.

He has suggested some ideas including:
– a “Gateway disabled” option that would prevent any messages being sent to any gateway.
– for the “Testing only” gateway – have separate configuration fields for the test keys. In this way, if the test keys are not populated, you won’t send anything to the live gateway by mistake – the live keys are only used if the the live gateway is selected. This makes it safer for users like me who don’t fully understand how the Testing gateway option works.

**Comment by dparker1005** [comment]
If this is a live site, we still want to process IPN/webhook messages for recurring payments which means we need real credentials active.

We now recommend using a staging site for testing. We have an article on setting up a staging site so that it doesn't interact with your live gateway here: https://www.paidmembershipspro.com/how-to-set-up-a-staging-environment-to-test-changes-and-new-features-for-your-membership-site/
