### ISSUE TITLE
Better Error Messaging for Stripe at Checkout

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#855]
A user would like us to include additional validation for Stripe Checkouts - https://stripe.com/docs/stripe-js/v2#bank-account-validation-helpers

**Comment by hbcondo** [comment]
None of the required fields (username, password, email) are undergoing any kind of client-side validation so this is not limited to just Stripe. @andrewlimaza verified this when responding to the original support ticket submitted here: https://www.paidmembershipspro.com/forums/topic/client-side-validation-helpers/

**Comment by hbcondo** [comment]
This issue also occurs on paidmembershipspro.com's member checkout web page. If no form fields are entered and the user clicks the "Submit and Check Out" button, a client-side call to Stripe is still made. This produces an error on the Stripe side so please implement their client-side helpers to prevent unnecessary calls to their API.

 https://www.paidmembershipspro.com/membership-checkout/?level=20

![image](https://user-images.githubusercontent.com/306958/52314278-d648a980-2966-11e9-85c6-dbd722320a9a.png)

**Comment by andrewlimaza** [comment]
Thank you for sharing this information with us, I'm really sorry about the inconvenience caused by this. I have marked this internally as important for our development team to take a look and resolve this issue as quickly as we can.

This may take a bit of time to figure out, test thoroughly and then release publicly.

You should get updates on this Github issue and a pre-release may be available in the near future.

**Comment by ideadude** [comment]
My thoughts here. I could be convinced otherwise.

I'm not as concerned about hitting the Stripe API extra times. The API is fast and they don't really limit things. We've had spammers on our site hitting checkout hundreds of times per minute and it didn't slow our site down. Stripe threatened to cut off access if it persisted for a week, but that's an extreme case, not a couple extra calls per checkout.

The errors show up in the console, but that's Stripes way of doing things. I don't think the average user is affected by errors in the console.

I think the only real reason to validate ahead of time would be to show better errors than Stripe is already showing.

Visually, it is difficult to show errors on the page in a way that would make them noticeable and nice looking across the different themes that could be used. We could show an error below the checkout button. And update fields to use the error css class in realtime/etc. You might want a popup anyway to make sure users see it. That's what Stripe does.

We could also improve the wording of the errors. Let me know if there are cases where the Stripe error is misleading or inefficient.

Otherwise, I kind of view this as the kind of thing that could be done in a custom checkout template. We can perhaps do a tutorial on how to do that.

We should also wait until the Stripe v3 and SCA/Payment Intents work is done.

**Comment by dparker1005** [comment]
Errors from Stripe are now shown to users in the `#pmpro_message` element by the `stripe.js` class.
