### ISSUE TITLE
BUG: Admin emails use member's name in greeting

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/paid-memberships-pro#885]
Admin notification emails for checkout such as `checkout_free_admin.html`  use the customers name instead of the admin's name. So for example the admin may receive an email that starts out `Dear John Smith ` (customers name) instead of the admin's name.

**Comment by andrewlimaza** [comment]
Does this occur with the Email Templates Admin Editor enabled? Had a similar issue with Approvals Add On and figured it out, just have to swop out a variable.

**Comment by hbcondo** [comment]
I am experiencing this same issue with the Email Templates Admin Editor enabled.

**Comment by andrewlimaza** [comment]
@hbcondo are you using any other Add Ons?

**Comment by hbcondo** [comment]
Yes:

- Add Member From Admin
- Email Templates Add On
- Subscription Delays Add On
- PMPro Reason For Cancelling

**Comment by ideadude** [comment]
Should be fixed in the latest version from these commits:

https://github.com/strangerstudios/paid-memberships-pro/commit/3e6a66f319fb6b2225dbb60e68a177cc57c71d76

https://github.com/strangerstudios/paid-memberships-pro/commit/a0d88721afe8c4ab42f32e1ce5423773004cf840

Please reopen if we missed anything.
