### ISSUE TITLE
Bug Issue: Cancelling in PayPal does not cancel memberships inside Paid Memberships Pro.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#896]
There have been a couple of reports that canceling automatic payments inside PayPal aren't canceling users membership levels inside Paid Memberships Pro (Even when IPN settings are correct).

Here are some recent topics about it:

+ https://wordpress.org/support/topic/bug-when-user-cancell-recurring-subscription-at-paypal/
+ https://www.paidmembershipspro.com/forums/topic/does-cancelling-paypal-recurring-payments-update-the-pmpro-system/

**Comment by ideadude** [comment]
If IPN is not setup or working, this will happen: https://www.paidmembershipspro.com/troubleshooting-paypal-ipn-issues-with-paypal-express-paypal-standard-or-paypal-website-payments-pro/

Follow up on the topic from our paid forums: "The issue was that an old plugin prepopulated the PayPal Notification URL with the wrong address."

The issue on .org seems related to custom code perhaps.

**Comment by hbcondo** [comment]
We are still experiencing this bug in 2021 even with the [latest PMP release](https://github.com/strangerstudios/paid-memberships-pro/releases/tag/v2.5.2). We implemented `define( 'PMPRO_IPN_DEBUG', true )` and successfully receive IPN Log emails with details of the order and the message:

> VERIFIED
> We've already processed this cancellation

 Please re-open this bug and fix.
