### ISSUE TITLE
Cancelling orders when changing from paid to free level.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#905]
Bug Issue: When you have a paid level and change to a free level, it cancels all previous orders.

**Steps to Recreate:**

1. Create orders that have an amount or signup for paid levels.
2. Sign up for a free membership level, all previous orders are set to cancelled.

**Comment by ideadude** [comment]
This is by design. Remember the cancel status on an order means that the associated subscription has been cancelled not the order itself perse. It's an issue we need to settle to make orders less confusing.

In the meantime, we recently updated the code to cancel ALL orders with the same subscription id to avoid cases where PMPro would find a "success" order for that sub id later in the future, e.g. when Stripe send the webhook about the sub cancelling.

https://github.com/strangerstudios/paid-memberships-pro/blob/dev/includes/functions.php#L972
