### ISSUE TITLE
Integrate with Elementor Builder Better

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/paid-memberships-pro#960]
A user requested to add "Require Membership" functionality to Elementor blocks such as their gallery, contact form etc.

**Comment by ideadude** [comment]
In general instead of adding "require membership" options to all widgets/blocks/sections/etc, we prefer to have a separate membership block that you can nest things under.

If this is possible with Elementor we could create this to include in the compat folder, but this is more of a feature vs compatibility. We could add a new add on to support this.

**Comment by andrewlimaza** [comment]
Thanks! Just going to post this for anyone that may come across this - https://developers.elementor.com/creating-a-new-widget/

**Comment by dparker1005** [comment]
We have created Elementor widget settings to hide widgets based on a user's membership level here:
https://github.com/strangerstudios/paid-memberships-pro/commit/c32de7f32e8e8748f693d004476f1393b6496707#diff-29dbf59520888caa1d996bf0803a0a49d7ec2d8b3d6654b54689cd02d6543d53
